name: aws login
author: EleSangwon
description: 'Use aws login in github action .'
inputs:
  REGION:
    description: 'Set AWS REGION'
    required: false
    default: 'ap-northeast-2'
  AWS_ROLE_ARN:
    description: 'Set AWS Assume Role arn'
    required: true
    default: 'arn:aws:iam::123456789:role/GithubActions'

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      id: credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ inputs.REGION }}
        role-to-assume: ${{ inputs.AWS_ROLE_ARN }}
        
