name: Slack
author: EleSangwon
description: 'Use slack job in github action .'
inputs:
  DEPLOY_JOB_STATUS:
    description: 'set deploy job status'
    required: true
    default: 'branch'
  ENVIRONMENT:
    description: 'set env'
    required: true
    default: 'develop'
  SLACK_WEBHOOK_URL:
    description: 'set slack webhook url'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: notify
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "text": "Deploy Result: ${{ inputs.DEPLOY_JOB_STATUS }} in environment: ${{ inputs.ENVIRONMENT }}, repository: ${{ github.repository }}.",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Deploy Result: ${{ inputs.DEPLOY_JOB_STATUS  }} in environment: ${{ inputs.ENVIRONMENT }}, repository: ${{ github.repository }}."
                }
              },
              {
                "type": "actions",
                "elements": [
                  {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "Approve for prod deploy"
                  },
                  "url" : "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        
        
