name: set-env
author: EleSangwon
description: 'Use set-environment job in github action .'
inputs:
  REF_TYPE:
    description: 'branch or tag'
    required: true
    default: 'branch'
  REF_NAME:
    description: 'develop or production'
    required: true
    default: 'develop'
outputs:
  set-env:
    description: 'Get env'
    value: ${{ steps.set-values.outputs.set-env }}
  set-tag:
    description: 'Get tag'
    value: ${{ steps.set-values.outputs.set-tag }}
  

runs:
  using: "composite"
  steps:
    - name: set env
      id: set-values
      shell: bash
      run: |
        if [[ ${{ inputs.REF_TYPE }} == "tag" ]]; then
            echo "set-env=qa" >> "$GITHUB_OUTPUT"
            echo "set-tag=${{ inputs.REF_NAME }}" >> "$GITHUB_OUTPUT"
            exit 0
        fi

        if [[ ${{ inputs.REF_TYPE }} == "branch" ]]; then
          if [[ ${{ inputs.REF_NAME }} == "develop" ]]; then
            echo "set-env=develop" >> "$GITHUB_OUTPUT"
            exit 0
          elif [[ ${{ inputs.REF_NAME }} == "production" ]]; then
            echo "set-env=staging" >> "$GITHUB_OUTPUT"
            exit 0
          fi
        fi
    - name: check output
      shell: bash
      run: |
        echo ${{ steps.set-values.outputs.set-env }}
        echo ${{ steps.set-values.outputs.set-tag }}
        
        
